### ISSUE TITLE
Relaxing  installation requirement maybe. 🧘

### ISSUE THREAD

**Issue by thierrymarianne** [mthom/scryer-shen#2]
Hey! 

After successful `raco setup` execution,
when running from the root directory the next command, 
> raco exe --cs -o shen ++lib racket/lang/reader repl.rkt  

I got the attached error related to collection 

```
raco exe --cs -o shen ++lib racket/lang/reader repl.rkt
repl.rkt:8:9: collection not found
  for module path: shen/lang/interposition-points
  collection: "shen/lang"
  in collection directories:
   /Users/shal/Library/Racket/8.12/collects
   /Applications/Racket v8.12/collects/
   ... [170 additional linked and package directories]
  location...:
   repl.rkt:8:9
  context...:
   /Applications/Racket v8.12/collects/compiler/embed.rkt:445:0: get-code
   /Applications/Racket v8.12/collects/racket/private/map.rkt:267:2: gen-for-each
   /Applications/Racket v8.12/collects/compiler/embed.rkt:1183:0: do-write-module-bundle
   /Applications/Racket v8.12/collects/compiler/embed.rkt:1663:15: write-module
   /Applications/Racket v8.12/collects/compiler/embed.rkt:1567:6
   /Applications/Racket v8.12/share/pkgs/compiler-lib/compiler/commands/exe.rkt:100:0
   body of "/Applications/Racket v8.12/share/pkgs/compiler-lib/compiler/commands/exe.rkt"
   /Applications/Racket v8.12/collects/raco/raco.rkt:41:0
   body of "/Applications/Racket v8.12/collects/raco/raco.rkt"
   body of "/Applications/Racket v8.12/collects/raco/main.rkt
```

Before realizing i had not copied `scryer-prolog` executable to `dist/bin`.

Would you like me to submit a pull-request 
embedding a `Makefile` or something else 
so that we could
  - check racket binary availability
  - check Scryer prolog binary availability
  - run `raco setup`
  - run `raco exe --cs -o shen ++lib racket/lang/reader repl.rkt`

by running a single target perhaps?

**Comment by mthom** [comment]
Yeah, I had that problem on my laptop too. I'm not sure how to resolve it apart from changing the "shen/lang" lines back to filename paths. @jagen31, could you please advise?

**Comment by jagen31** [comment]
Ah, so, you have to install the package first with
`raco pkg install ./scryer-shen` from just outside the directory....

once you push up scryer-shen to the main package catalog, it will just be `raco pkg install scryer-shen` and it will pull it from there, instead of needing the files locally.

**Comment by jagen31** [comment]
to remove it- `raco pkg remove scryer-shen`.

**Comment by thierrymarianne** [comment]
Thank you folks! 

https://github.com/mthom/scryer-shen/pull/3 has been opened even though it is not clear if a makefile is really something worth introducing.   

Still, it will be there for grab if needed, 
same for this issue self-documentation. 

Both suggestions appear to work like a charm out 
of a cloned `prolog-shen` project directory:
 - `raco pkg install scryer-shen`
 - `raco pkg remove scryer-shen`

I'll submit another pull-request for modifying the README file
depending on preferences related to Makefile approach 
(for instance about requiring to have Make on the host machine 😅).
